/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import io.keen.api.*;
import io.keen.api.models.*;
import io.keen.api.exceptions.*;
import io.keen.api.http.client.HttpClient;
import io.keen.api.http.client.HttpContext;
import io.keen.api.http.request.HttpRequest;
import io.keen.api.http.response.HttpResponse;
import io.keen.api.http.response.HttpStringResponse;
import io.keen.api.http.client.APICallBack;
import io.keen.api.controllers.syncwrapper.APICallBackCatcher;

public class VersionsResourceController extends BaseController {    
    //private static variables for the singleton pattern
    private static Object syncObject = new Object();
    private static VersionsResourceController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the VersionsResourceController class 
     */
    public static VersionsResourceController getInstance() {
        synchronized (syncObject) {
            if (null == instance) {
                instance = new VersionsResourceController();
            }
        }
        return instance;
    }

    /**
     * Returns the available API versions. Please only use API version 3.0. Versions 1.0 and 2.0 have been deprecated.
     * @return    Returns the List<GetAPIVersionResponse> response from the API call 
     */
    public List<GetAPIVersionResponse> getAPIVersion(
    ) throws Throwable {
        APICallBackCatcher<List<GetAPIVersionResponse>> callback = new APICallBackCatcher<List<GetAPIVersionResponse>>();
        getAPIVersionAsync(callback);
        if(!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }

    /**
     * Returns the available API versions. Please only use API version 3.0. Versions 1.0 and 2.0 have been deprecated.
     * @return    Returns the void response from the API call 
     */
    public void getAPIVersionAsync(
                final APICallBack<List<GetAPIVersionResponse>> callBack
    ) {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;
        
        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 5095494215826716213L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "Authorization", Configuration.authorization );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            List<GetAPIVersionResponse> _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<List<GetAPIVersionResponse>>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}