/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AvaliableChildProjectResourceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5153018508178511395L;
    private String projectsResourceUrl;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("projects_resource_url")
    public String getProjectsResourceUrl ( ) { 
        return this.projectsResourceUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("projects_resource_url")
    public void setProjectsResourceUrl (String value) { 
        this.projectsResourceUrl = value;
    }
 
}
 