/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class AvaliableChildProjectResourceResponseBuilder {
    //the instance to build
    private AvaliableChildProjectResourceResponse avaliableChildProjectResourceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AvaliableChildProjectResourceResponseBuilder() {
        avaliableChildProjectResourceResponse = new AvaliableChildProjectResourceResponse();
    }

    public AvaliableChildProjectResourceResponseBuilder projectsResourceUrl(String projectsResourceUrl) {
        avaliableChildProjectResourceResponse.setProjectsResourceUrl(projectsResourceUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AvaliableChildProjectResourceResponse build() {
        return avaliableChildProjectResourceResponse;
    }
}