/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class CountResponseBuilder {
    //the instance to build
    private CountResponse countResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CountResponseBuilder() {
        countResponse = new CountResponse();
    }

    public CountResponseBuilder result(int result) {
        countResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CountResponse build() {
        return countResponse;
    }
}