/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class CreatedResponseBuilder {
    //the instance to build
    private CreatedResponse createdResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CreatedResponseBuilder() {
        createdResponse = new CreatedResponse();
    }

    public CreatedResponseBuilder created(boolean created) {
        createdResponse.setCreated(created);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatedResponse build() {
        return createdResponse;
    }
}