/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreatedResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4924009713153654006L;
    private boolean created;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("created")
    public boolean getCreated ( ) { 
        return this.created;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("created")
    public void setCreated (boolean value) { 
        this.created = value;
    }
 
}
 