/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class DeleteEventCollectionResourceInputBuilder {
    //the instance to build
    private DeleteEventCollectionResourceInput deleteEventCollectionResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public DeleteEventCollectionResourceInputBuilder() {
        deleteEventCollectionResourceInput = new DeleteEventCollectionResourceInput();
    }

    public DeleteEventCollectionResourceInputBuilder eventCollection(String eventCollection) {
        deleteEventCollectionResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public DeleteEventCollectionResourceInputBuilder projectId(String projectId) {
        deleteEventCollectionResourceInput.setProjectId(projectId);
        return this;
    }

    public DeleteEventCollectionResourceInputBuilder version(String version) {
        deleteEventCollectionResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeleteEventCollectionResourceInput build() {
        return deleteEventCollectionResourceInput;
    }
}