/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class DeleteSavedQueryRowResourceInputBuilder {
    //the instance to build
    private DeleteSavedQueryRowResourceInput deleteSavedQueryRowResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public DeleteSavedQueryRowResourceInputBuilder() {
        deleteSavedQueryRowResourceInput = new DeleteSavedQueryRowResourceInput();
    }

    public DeleteSavedQueryRowResourceInputBuilder projectId(String projectId) {
        deleteSavedQueryRowResourceInput.setProjectId(projectId);
        return this;
    }

    public DeleteSavedQueryRowResourceInputBuilder savedQueryName(String savedQueryName) {
        deleteSavedQueryRowResourceInput.setSavedQueryName(savedQueryName);
        return this;
    }

    public DeleteSavedQueryRowResourceInputBuilder version(String version) {
        deleteSavedQueryRowResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeleteSavedQueryRowResourceInput build() {
        return deleteSavedQueryRowResourceInput;
    }
}