/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class DeletePropertyResourceInputBuilder {
    //the instance to build
    private DeletePropertyResourceInput deletePropertyResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public DeletePropertyResourceInputBuilder() {
        deletePropertyResourceInput = new DeletePropertyResourceInput();
    }

    public DeletePropertyResourceInputBuilder eventCollection(String eventCollection) {
        deletePropertyResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public DeletePropertyResourceInputBuilder projectId(String projectId) {
        deletePropertyResourceInput.setProjectId(projectId);
        return this;
    }

    public DeletePropertyResourceInputBuilder propertyName(String propertyName) {
        deletePropertyResourceInput.setPropertyName(propertyName);
        return this;
    }

    public DeletePropertyResourceInputBuilder version(String version) {
        deletePropertyResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeletePropertyResourceInput build() {
        return deletePropertyResourceInput;
    }
}