/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class FiltersBuilder {
    //the instance to build
    private Filters filters;

    /**
     * Default constructor to initialize the instance
     */
    public FiltersBuilder() {
        filters = new Filters();
    }

    /**
     * he name of the property on which you?d like to filte
     */
    public FiltersBuilder operator(Operators operator) {
        filters.setOperator(operator);
        return this;
    }

    /**
     * he name of the property on which you?d like to filte
     */
    public FiltersBuilder propertyName(String propertyName) {
        filters.setPropertyName(propertyName);
        return this;
    }

    /**
     * the value to compare to the property specified in ?property_name?.
     */
    public FiltersBuilder propertyValue(LinkedHashMap<String, Object> propertyValue) {
        filters.setPropertyValue(propertyValue);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Filters build() {
        return filters;
    }
}