/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Filters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4950380863317314549L;
    private Operators operator;
    private String propertyName;
    private LinkedHashMap<String, Object> propertyValue;
    /** GETTER
     * he name of the property on which you?d like to filte
     */
    @JsonGetter("operator")
    public Operators getOperator ( ) { 
        return this.operator;
    }
    
    /** SETTER
     * he name of the property on which you?d like to filte
     */
    @JsonSetter("operator")
    public void setOperator (Operators value) { 
        this.operator = value;
    }
 
    /** GETTER
     * he name of the property on which you?d like to filte
     */
    @JsonGetter("property_name")
    public String getPropertyName ( ) { 
        return this.propertyName;
    }
    
    /** SETTER
     * he name of the property on which you?d like to filte
     */
    @JsonSetter("property_name")
    public void setPropertyName (String value) { 
        this.propertyName = value;
    }
 
    /** GETTER
     * the value to compare to the property specified in ?property_name?.
     */
    @JsonGetter("property_value")
    public LinkedHashMap<String, Object> getPropertyValue ( ) { 
        return this.propertyValue;
    }
    
    /** SETTER
     * the value to compare to the property specified in ?property_name?.
     */
    @JsonSetter("property_value")
    public void setPropertyValue (LinkedHashMap<String, Object> value) { 
        this.propertyValue = value;
    }
 
}
 