/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetAverageResourceInputBuilder {
    //the instance to build
    private GetAverageResourceInput getAverageResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetAverageResourceInputBuilder() {
        getAverageResourceInput = new GetAverageResourceInput();
    }

    /**
     * - The name of the event collection you are analyzing.
     */
    public GetAverageResourceInputBuilder eventCollection(String eventCollection) {
        getAverageResourceInput.setEventCollection(eventCollection);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape.
     */
    public GetAverageResourceInputBuilder interval(String interval) {
        getAverageResourceInput.setInterval(interval);
        return this;
    }

    public GetAverageResourceInputBuilder projectId(String projectId) {
        getAverageResourceInput.setProjectId(projectId);
        return this;
    }

    /**
     * The name of the property you are analyzing.
     */
    public GetAverageResourceInputBuilder targetProperty(String targetProperty) {
        getAverageResourceInput.setTargetProperty(targetProperty);
        return this;
    }

    public GetAverageResourceInputBuilder version(String version) {
        getAverageResourceInput.setVersion(version);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetAverageResourceInputBuilder filters(String filters) {
        getAverageResourceInput.setFilters(filters);
        return this;
    }

    /**
     * The group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format. Read more about Group By to learn more.
     */
    public GetAverageResourceInputBuilder groupBy(String groupBy) {
        getAverageResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetAverageResourceInputBuilder timeframe(String timeframe) {
        getAverageResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetAverageResourceInputBuilder timezone(String timezone) {
        getAverageResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetAverageResourceInput build() {
        return getAverageResourceInput;
    }
}