/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetAPIVersionResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4766826907781203543L;
    private boolean isPublic;
    private String url;
    private String version;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("is_public")
    public boolean getIsPublic ( ) { 
        return this.isPublic;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("is_public")
    public void setIsPublic (boolean value) { 
        this.isPublic = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("version")
    public String getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("version")
    public void setVersion (String value) { 
        this.version = value;
    }
 
}
 