/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetAPIVersionResponseBuilder {
    //the instance to build
    private GetAPIVersionResponse getAPIVersionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetAPIVersionResponseBuilder() {
        getAPIVersionResponse = new GetAPIVersionResponse();
    }

    public GetAPIVersionResponseBuilder isPublic(boolean isPublic) {
        getAPIVersionResponse.setIsPublic(isPublic);
        return this;
    }

    public GetAPIVersionResponseBuilder url(String url) {
        getAPIVersionResponse.setUrl(url);
        return this;
    }

    public GetAPIVersionResponseBuilder version(String version) {
        getAPIVersionResponse.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetAPIVersionResponse build() {
        return getAPIVersionResponse;
    }
}