/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetCountUniqueResourceInputBuilder {
    //the instance to build
    private GetCountUniqueResourceInput getCountUniqueResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCountUniqueResourceInputBuilder() {
        getCountUniqueResourceInput = new GetCountUniqueResourceInput();
    }

    /**
     * The name of the event collection you are analyzing.
     */
    public GetCountUniqueResourceInputBuilder eventCollection(String eventCollection) {
        getCountUniqueResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public GetCountUniqueResourceInputBuilder projectId(String projectId) {
        getCountUniqueResourceInput.setProjectId(projectId);
        return this;
    }

    /**
     * The name of the property you are analyzing.
     */
    public GetCountUniqueResourceInputBuilder targetProperty(String targetProperty) {
        getCountUniqueResourceInput.setTargetProperty(targetProperty);
        return this;
    }

    public GetCountUniqueResourceInputBuilder version(String version) {
        getCountUniqueResourceInput.setVersion(version);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape.
     */
    public GetCountUniqueResourceInputBuilder interval(String interval) {
        getCountUniqueResourceInput.setInterval(interval);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetCountUniqueResourceInputBuilder filters(String filters) {
        getCountUniqueResourceInput.setFilters(filters);
        return this;
    }

    /**
     * he group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format
     */
    public GetCountUniqueResourceInputBuilder groupBy(String groupBy) {
        getCountUniqueResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetCountUniqueResourceInputBuilder timeframe(String timeframe) {
        getCountUniqueResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetCountUniqueResourceInputBuilder timezone(String timezone) {
        getCountUniqueResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCountUniqueResourceInput build() {
        return getCountUniqueResourceInput;
    }
}