/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetCountResourceInputBuilder {
    //the instance to build
    private GetCountResourceInput getCountResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCountResourceInputBuilder() {
        getCountResourceInput = new GetCountResourceInput();
    }

    /**
     * he name of the event collection you are analyzing.
     */
    public GetCountResourceInputBuilder eventCollection(String eventCollection) {
        getCountResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public GetCountResourceInputBuilder projectId(String projectId) {
        getCountResourceInput.setProjectId(projectId);
        return this;
    }

    public GetCountResourceInputBuilder version(String version) {
        getCountResourceInput.setVersion(version);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetCountResourceInputBuilder filters(String filters) {
        getCountResourceInput.setFilters(filters);
        return this;
    }

    /**
     * The group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format. Read more about Group By to learn more.
     */
    public GetCountResourceInputBuilder groupBy(String groupBy) {
        getCountResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape.
     */
    public GetCountResourceInputBuilder interval(String interval) {
        getCountResourceInput.setInterval(interval);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetCountResourceInputBuilder timeframe(String timeframe) {
        getCountResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetCountResourceInputBuilder timezone(String timezone) {
        getCountResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCountResourceInput build() {
        return getCountResourceInput;
    }
}