/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetExtractionResourceInputBuilder {
    //the instance to build
    private GetExtractionResourceInput getExtractionResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetExtractionResourceInputBuilder() {
        getExtractionResourceInput = new GetExtractionResourceInput();
    }

    /**
     * The name of the event collection you are analyzing.
     */
    public GetExtractionResourceInputBuilder eventCollection(String eventCollection) {
        getExtractionResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public GetExtractionResourceInputBuilder projectId(String projectId) {
        getExtractionResourceInput.setProjectId(projectId);
        return this;
    }

    public GetExtractionResourceInputBuilder version(String version) {
        getExtractionResourceInput.setVersion(version);
        return this;
    }

    /**
     * If an email address is specified, an email will be sent to it when your extraction is ready for download. If email is not specified, your extraction will be processed synchronously and your data will be returned as JSON.
     */
    public GetExtractionResourceInputBuilder email(String email) {
        getExtractionResourceInput.setEmail(email);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetExtractionResourceInputBuilder filters(String filters) {
        getExtractionResourceInput.setFilters(filters);
        return this;
    }

    /**
     * An integer containing the number of most recent events to extract.
     */
    public GetExtractionResourceInputBuilder latest(Integer latest) {
        getExtractionResourceInput.setLatest(latest);
        return this;
    }

    /**
     * A URL-encoded array of strings containing properties you wish to extract. If this parameter is omitted, all properties will be returned.
     */
    public GetExtractionResourceInputBuilder propertyNames(String propertyNames) {
        getExtractionResourceInput.setPropertyNames(propertyNames);
        return this;
    }

    /**
     * A Timeframe specifies the events to use for analysis based on a window of time.
     */
    public GetExtractionResourceInputBuilder timeframe(String timeframe) {
        getExtractionResourceInput.setTimeframe(timeframe);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetExtractionResourceInput build() {
        return getExtractionResourceInput;
    }
}