/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetEventResourceInputBuilder {
    //the instance to build
    private GetEventResourceInput getEventResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetEventResourceInputBuilder() {
        getEventResourceInput = new GetEventResourceInput();
    }

    public GetEventResourceInputBuilder projectId(String projectId) {
        getEventResourceInput.setProjectId(projectId);
        return this;
    }

    public GetEventResourceInputBuilder version(String version) {
        getEventResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetEventResourceInput build() {
        return getEventResourceInput;
    }
}