/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetFunnelResourceInputBuilder {
    //the instance to build
    private GetFunnelResourceInput getFunnelResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetFunnelResourceInputBuilder() {
        getFunnelResourceInput = new GetFunnelResourceInput();
    }

    public GetFunnelResourceInputBuilder projectId(String projectId) {
        getFunnelResourceInput.setProjectId(projectId);
        return this;
    }

    public GetFunnelResourceInputBuilder steps(String steps) {
        getFunnelResourceInput.setSteps(steps);
        return this;
    }

    public GetFunnelResourceInputBuilder version(String version) {
        getFunnelResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetFunnelResourceInput build() {
        return getFunnelResourceInput;
    }
}