/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetFunnelResourceResponseBuilder {
    //the instance to build
    private GetFunnelResourceResponse getFunnelResourceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetFunnelResourceResponseBuilder() {
        getFunnelResourceResponse = new GetFunnelResourceResponse();
    }

    public GetFunnelResourceResponseBuilder result(List<Integer> result) {
        getFunnelResourceResponse.setResult(result);
        return this;
    }

    public GetFunnelResourceResponseBuilder steps(List<Steps> steps) {
        getFunnelResourceResponse.setSteps(steps);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetFunnelResourceResponse build() {
        return getFunnelResourceResponse;
    }
}