/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetFunnelResourceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5685642570452403592L;
    private List<Integer> result;
    private List<Steps> steps;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public List<Integer> getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    public void setResult (List<Integer> value) { 
        this.result = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("steps")
    public List<Steps> getSteps ( ) { 
        return this.steps;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("steps")
    public void setSteps (List<Steps> value) { 
        this.steps = value;
    }
 
}
 