/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetMinimumResourceInputBuilder {
    //the instance to build
    private GetMinimumResourceInput getMinimumResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetMinimumResourceInputBuilder() {
        getMinimumResourceInput = new GetMinimumResourceInput();
    }

    public GetMinimumResourceInputBuilder projectId(String projectId) {
        getMinimumResourceInput.setProjectId(projectId);
        return this;
    }

    public GetMinimumResourceInputBuilder version(String version) {
        getMinimumResourceInput.setVersion(version);
        return this;
    }

    /**
     * The name of the event collection you are analyzing.
     */
    public GetMinimumResourceInputBuilder eventCollection(String eventCollection) {
        getMinimumResourceInput.setEventCollection(eventCollection);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetMinimumResourceInputBuilder filters(String filters) {
        getMinimumResourceInput.setFilters(filters);
        return this;
    }

    /**
     * The group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format. Read more about Group By to learn more.
     */
    public GetMinimumResourceInputBuilder groupBy(String groupBy) {
        getMinimumResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape
     */
    public GetMinimumResourceInputBuilder interval(String interval) {
        getMinimumResourceInput.setInterval(interval);
        return this;
    }

    /**
     * The name of the property you are analyzing.
     */
    public GetMinimumResourceInputBuilder targetProperty(String targetProperty) {
        getMinimumResourceInput.setTargetProperty(targetProperty);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetMinimumResourceInputBuilder timeframe(String timeframe) {
        getMinimumResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetMinimumResourceInputBuilder timezone(String timezone) {
        getMinimumResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetMinimumResourceInput build() {
        return getMinimumResourceInput;
    }
}