/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetMaximumResourceInputBuilder {
    //the instance to build
    private GetMaximumResourceInput getMaximumResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetMaximumResourceInputBuilder() {
        getMaximumResourceInput = new GetMaximumResourceInput();
    }

    public GetMaximumResourceInputBuilder projectId(String projectId) {
        getMaximumResourceInput.setProjectId(projectId);
        return this;
    }

    public GetMaximumResourceInputBuilder version(String version) {
        getMaximumResourceInput.setVersion(version);
        return this;
    }

    /**
     * The name of the event collection you are analyzing.
     */
    public GetMaximumResourceInputBuilder eventCollection(String eventCollection) {
        getMaximumResourceInput.setEventCollection(eventCollection);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetMaximumResourceInputBuilder filters(String filters) {
        getMaximumResourceInput.setFilters(filters);
        return this;
    }

    /**
     * The group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format. Read more about Group By to learn more.
     */
    public GetMaximumResourceInputBuilder groupBy(String groupBy) {
        getMaximumResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape.
     */
    public GetMaximumResourceInputBuilder interval(String interval) {
        getMaximumResourceInput.setInterval(interval);
        return this;
    }

    /**
     * The name of the property you are analyzing.
     */
    public GetMaximumResourceInputBuilder targetProperty(String targetProperty) {
        getMaximumResourceInput.setTargetProperty(targetProperty);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetMaximumResourceInputBuilder timeframe(String timeframe) {
        getMaximumResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetMaximumResourceInputBuilder timezone(String timezone) {
        getMaximumResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetMaximumResourceInput build() {
        return getMaximumResourceInput;
    }
}