/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetPropertyResourceInputBuilder {
    //the instance to build
    private GetPropertyResourceInput getPropertyResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetPropertyResourceInputBuilder() {
        getPropertyResourceInput = new GetPropertyResourceInput();
    }

    public GetPropertyResourceInputBuilder eventCollection(String eventCollection) {
        getPropertyResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public GetPropertyResourceInputBuilder projectId(String projectId) {
        getPropertyResourceInput.setProjectId(projectId);
        return this;
    }

    public GetPropertyResourceInputBuilder propertyName(String propertyName) {
        getPropertyResourceInput.setPropertyName(propertyName);
        return this;
    }

    public GetPropertyResourceInputBuilder version(String version) {
        getPropertyResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPropertyResourceInput build() {
        return getPropertyResourceInput;
    }
}