/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetPropertyResourceResponseBuilder {
    //the instance to build
    private GetPropertyResourceResponse getPropertyResourceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetPropertyResourceResponseBuilder() {
        getPropertyResourceResponse = new GetPropertyResourceResponse();
    }

    public GetPropertyResourceResponseBuilder propertyName(String propertyName) {
        getPropertyResourceResponse.setPropertyName(propertyName);
        return this;
    }

    public GetPropertyResourceResponseBuilder type(String type) {
        getPropertyResourceResponse.setType(type);
        return this;
    }

    public GetPropertyResourceResponseBuilder url(String url) {
        getPropertyResourceResponse.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPropertyResourceResponse build() {
        return getPropertyResourceResponse;
    }
}