/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetProjectAccessibleResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5449163684368112202L;
    private String apiKey;
    private List<String> events;
    private String eventsUrl;
    private String id;
    private String name;
    private String organizationId;
    private String partnersUrl;
    private String queriesUrl;
    private List<String> savedQueries;
    private String savedQueriesUrl;
    private String url;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("api_key")
    public String getApiKey ( ) { 
        return this.apiKey;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("api_key")
    public void setApiKey (String value) { 
        this.apiKey = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("events")
    public List<String> getEvents ( ) { 
        return this.events;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("events")
    public void setEvents (List<String> value) { 
        this.events = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("events_url")
    public String getEventsUrl ( ) { 
        return this.eventsUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("events_url")
    public void setEventsUrl (String value) { 
        this.eventsUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("organization_id")
    public String getOrganizationId ( ) { 
        return this.organizationId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("organization_id")
    public void setOrganizationId (String value) { 
        this.organizationId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("partners_url")
    public String getPartnersUrl ( ) { 
        return this.partnersUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("partners_url")
    public void setPartnersUrl (String value) { 
        this.partnersUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("queries_url")
    public String getQueriesUrl ( ) { 
        return this.queriesUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("queries_url")
    public void setQueriesUrl (String value) { 
        this.queriesUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saved_queries")
    public List<String> getSavedQueries ( ) { 
        return this.savedQueries;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saved_queries")
    public void setSavedQueries (List<String> value) { 
        this.savedQueries = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saved_queries_url")
    public String getSavedQueriesUrl ( ) { 
        return this.savedQueriesUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saved_queries_url")
    public void setSavedQueriesUrl (String value) { 
        this.savedQueriesUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
}
 