/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetProjectRowResourceInputBuilder {
    //the instance to build
    private GetProjectRowResourceInput getProjectRowResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetProjectRowResourceInputBuilder() {
        getProjectRowResourceInput = new GetProjectRowResourceInput();
    }

    public GetProjectRowResourceInputBuilder projectId(String projectId) {
        getProjectRowResourceInput.setProjectId(projectId);
        return this;
    }

    public GetProjectRowResourceInputBuilder version(String version) {
        getProjectRowResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetProjectRowResourceInput build() {
        return getProjectRowResourceInput;
    }
}