/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetSavedQueryRowResourceInputBuilder {
    //the instance to build
    private GetSavedQueryRowResourceInput getSavedQueryRowResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetSavedQueryRowResourceInputBuilder() {
        getSavedQueryRowResourceInput = new GetSavedQueryRowResourceInput();
    }

    public GetSavedQueryRowResourceInputBuilder analysisType(String analysisType) {
        getSavedQueryRowResourceInput.setAnalysisType(analysisType);
        return this;
    }

    public GetSavedQueryRowResourceInputBuilder projectId(String projectId) {
        getSavedQueryRowResourceInput.setProjectId(projectId);
        return this;
    }

    public GetSavedQueryRowResourceInputBuilder savedQueryName(String savedQueryName) {
        getSavedQueryRowResourceInput.setSavedQueryName(savedQueryName);
        return this;
    }

    public GetSavedQueryRowResourceInputBuilder version(String version) {
        getSavedQueryRowResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSavedQueryRowResourceInput build() {
        return getSavedQueryRowResourceInput;
    }
}