/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetSelectUniqueResourceInputBuilder {
    //the instance to build
    private GetSelectUniqueResourceInput getSelectUniqueResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetSelectUniqueResourceInputBuilder() {
        getSelectUniqueResourceInput = new GetSelectUniqueResourceInput();
    }

    /**
     * The name of the event collection you are analyzing.
     */
    public GetSelectUniqueResourceInputBuilder eventCollection(String eventCollection) {
        getSelectUniqueResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public GetSelectUniqueResourceInputBuilder projectId(String projectId) {
        getSelectUniqueResourceInput.setProjectId(projectId);
        return this;
    }

    /**
     * the name of the property you are analyzing.
     */
    public GetSelectUniqueResourceInputBuilder targetProperty(String targetProperty) {
        getSelectUniqueResourceInput.setTargetProperty(targetProperty);
        return this;
    }

    public GetSelectUniqueResourceInputBuilder version(String version) {
        getSelectUniqueResourceInput.setVersion(version);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetSelectUniqueResourceInputBuilder filters(String filters) {
        getSelectUniqueResourceInput.setFilters(filters);
        return this;
    }

    /**
     * The group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format. Read more about Group By to learn more.
     */
    public GetSelectUniqueResourceInputBuilder groupBy(String groupBy) {
        getSelectUniqueResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape.
     */
    public GetSelectUniqueResourceInputBuilder interval(String interval) {
        getSelectUniqueResourceInput.setInterval(interval);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetSelectUniqueResourceInputBuilder timeframe(String timeframe) {
        getSelectUniqueResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetSelectUniqueResourceInputBuilder timezone(String timezone) {
        getSelectUniqueResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSelectUniqueResourceInput build() {
        return getSelectUniqueResourceInput;
    }
}