/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetSavedQueryRowResultResourceInputBuilder {
    //the instance to build
    private GetSavedQueryRowResultResourceInput getSavedQueryRowResultResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetSavedQueryRowResultResourceInputBuilder() {
        getSavedQueryRowResultResourceInput = new GetSavedQueryRowResultResourceInput();
    }

    public GetSavedQueryRowResultResourceInputBuilder projectId(String projectId) {
        getSavedQueryRowResultResourceInput.setProjectId(projectId);
        return this;
    }

    public GetSavedQueryRowResultResourceInputBuilder savedQueryName(String savedQueryName) {
        getSavedQueryRowResultResourceInput.setSavedQueryName(savedQueryName);
        return this;
    }

    public GetSavedQueryRowResultResourceInputBuilder version(String version) {
        getSavedQueryRowResultResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSavedQueryRowResultResourceInput build() {
        return getSavedQueryRowResultResourceInput;
    }
}