/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetSavedQueriesListResourceInputBuilder {
    //the instance to build
    private GetSavedQueriesListResourceInput getSavedQueriesListResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetSavedQueriesListResourceInputBuilder() {
        getSavedQueriesListResourceInput = new GetSavedQueriesListResourceInput();
    }

    public GetSavedQueriesListResourceInputBuilder projectId(String projectId) {
        getSavedQueriesListResourceInput.setProjectId(projectId);
        return this;
    }

    public GetSavedQueriesListResourceInputBuilder version(String version) {
        getSavedQueriesListResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSavedQueriesListResourceInput build() {
        return getSavedQueriesListResourceInput;
    }
}