/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class GetSumResourceInputBuilder {
    //the instance to build
    private GetSumResourceInput getSumResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetSumResourceInputBuilder() {
        getSumResourceInput = new GetSumResourceInput();
    }

    /**
     * Read Key for the project containing the data you are analyzing. See Authentication for more information
     */
    public GetSumResourceInputBuilder apiKey(String apiKey) {
        getSumResourceInput.setApiKey(apiKey);
        return this;
    }

    /**
     * he name of the event collection you are analyzing.
     */
    public GetSumResourceInputBuilder eventCollection(String eventCollection) {
        getSumResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public GetSumResourceInputBuilder projectId(String projectId) {
        getSumResourceInput.setProjectId(projectId);
        return this;
    }

    /**
     * The name of the property you are analyzing.
     */
    public GetSumResourceInputBuilder targetProperty(String targetProperty) {
        getSumResourceInput.setTargetProperty(targetProperty);
        return this;
    }

    public GetSumResourceInputBuilder version(String version) {
        getSumResourceInput.setVersion(version);
        return this;
    }

    /**
     * Filters are used to narrow down the events used in an analysis request based on event property values.
     */
    public GetSumResourceInputBuilder filters(String filters) {
        getSumResourceInput.setFilters(filters);
        return this;
    }

    /**
     * The group_by parameter specifies the name of a property by which you would like to group the results. Using this parameter changes the response format. Read more about Group By to learn more.
     */
    public GetSumResourceInputBuilder groupBy(String groupBy) {
        getSumResourceInput.setGroupBy(groupBy);
        return this;
    }

    /**
     * An Interval specifies the size of time block to break a response into. This will cause a change in the response shape.
     */
    public GetSumResourceInputBuilder interval(String interval) {
        getSumResourceInput.setInterval(interval);
        return this;
    }

    /**
     * Similar to filters, a Timeframe is used to narrow down the events used in an analysis request based on the time that the event occurred.
     */
    public GetSumResourceInputBuilder timeframe(String timeframe) {
        getSumResourceInput.setTimeframe(timeframe);
        return this;
    }

    /**
     * Modifies the timeframe filters for Relative Timeframes to match a specific timezone.
     */
    public GetSumResourceInputBuilder timezone(String timezone) {
        getSumResourceInput.setTimezone(timezone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSumResourceInput build() {
        return getSumResourceInput;
    }
}