/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class PostEventResourceInputBuilder {
    //the instance to build
    private PostEventResourceInput postEventResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public PostEventResourceInputBuilder() {
        postEventResourceInput = new PostEventResourceInput();
    }

    /**
     * JSON arrays of events
     */
    public PostEventResourceInputBuilder eventsBody(Object eventsBody) {
        postEventResourceInput.setEventsBody(eventsBody);
        return this;
    }

    public PostEventResourceInputBuilder projectId(String projectId) {
        postEventResourceInput.setProjectId(projectId);
        return this;
    }

    public PostEventResourceInputBuilder version(String version) {
        postEventResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PostEventResourceInput build() {
        return postEventResourceInput;
    }
}