/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class PostWardrobeResourceInputBuilder {
    //the instance to build
    private PostWardrobeResourceInput postWardrobeResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public PostWardrobeResourceInputBuilder() {
        postWardrobeResourceInput = new PostWardrobeResourceInput();
    }

    /**
     * Single JSON event
     */
    public PostWardrobeResourceInputBuilder body(Object body) {
        postWardrobeResourceInput.setBody(body);
        return this;
    }

    public PostWardrobeResourceInputBuilder projectId(String projectId) {
        postWardrobeResourceInput.setProjectId(projectId);
        return this;
    }

    public PostWardrobeResourceInputBuilder version(String version) {
        postWardrobeResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PostWardrobeResourceInput build() {
        return postWardrobeResourceInput;
    }
}