/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class PostEventCollectionResourceInputBuilder {
    //the instance to build
    private PostEventCollectionResourceInput postEventCollectionResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public PostEventCollectionResourceInputBuilder() {
        postEventCollectionResourceInput = new PostEventCollectionResourceInput();
    }

    /**
     * Single JSON event
     */
    public PostEventCollectionResourceInputBuilder eventCollection(String eventCollection) {
        postEventCollectionResourceInput.setEventCollection(eventCollection);
        return this;
    }

    public PostEventCollectionResourceInputBuilder eventBody(Object eventBody) {
        postEventCollectionResourceInput.setEventBody(eventBody);
        return this;
    }

    public PostEventCollectionResourceInputBuilder projectId(String projectId) {
        postEventCollectionResourceInput.setProjectId(projectId);
        return this;
    }

    public PostEventCollectionResourceInputBuilder version(String version) {
        postEventCollectionResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PostEventCollectionResourceInput build() {
        return postEventCollectionResourceInput;
    }
}