/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PutSavedQueryRowResourceInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5211632237051086436L;
    private String analysisType;
    private Object body;
    private String projectId;
    private String savedQueryName;
    private String version;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("analysis_type")
    public String getAnalysisType ( ) { 
        return this.analysisType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("analysis_type")
    public void setAnalysisType (String value) { 
        this.analysisType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Body")
    public Object getBody ( ) { 
        return this.body;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Body")
    public void setBody (Object value) { 
        this.body = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("project_id")
    public String getProjectId ( ) { 
        return this.projectId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("project_id")
    public void setProjectId (String value) { 
        this.projectId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saved_query_name")
    public String getSavedQueryName ( ) { 
        return this.savedQueryName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saved_query_name")
    public void setSavedQueryName (String value) { 
        this.savedQueryName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("version")
    public String getVersion ( ) { 
        return this.version;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("version")
    public void setVersion (String value) { 
        this.version = value;
    }
 
}
 