/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class PutSavedQueryRowResourceInputBuilder {
    //the instance to build
    private PutSavedQueryRowResourceInput putSavedQueryRowResourceInput;

    /**
     * Default constructor to initialize the instance
     */
    public PutSavedQueryRowResourceInputBuilder() {
        putSavedQueryRowResourceInput = new PutSavedQueryRowResourceInput();
    }

    public PutSavedQueryRowResourceInputBuilder analysisType(String analysisType) {
        putSavedQueryRowResourceInput.setAnalysisType(analysisType);
        return this;
    }

    public PutSavedQueryRowResourceInputBuilder body(Object body) {
        putSavedQueryRowResourceInput.setBody(body);
        return this;
    }

    public PutSavedQueryRowResourceInputBuilder projectId(String projectId) {
        putSavedQueryRowResourceInput.setProjectId(projectId);
        return this;
    }

    public PutSavedQueryRowResourceInputBuilder savedQueryName(String savedQueryName) {
        putSavedQueryRowResourceInput.setSavedQueryName(savedQueryName);
        return this;
    }

    public PutSavedQueryRowResourceInputBuilder version(String version) {
        putSavedQueryRowResourceInput.setVersion(version);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PutSavedQueryRowResourceInput build() {
        return putSavedQueryRowResourceInput;
    }
}