/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SavedQueriesListResourceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4978665740354752112L;
    private String analysisType;
    private Date createdDate;
    private String eventCollection;
    private List<String> filters;
    private String interval;
    private Date lastModifiedDate;
    private String queryName;
    private String queryType;
    private Date timeframe;
    private Urls urls;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("analysis_type")
    public String getAnalysisType ( ) { 
        return this.analysisType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("analysis_type")
    public void setAnalysisType (String value) { 
        this.analysisType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("created_date")
    public Date getCreatedDate ( ) { 
        return this.createdDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("created_date")
    public void setCreatedDate (Date value) { 
        this.createdDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("event_collection")
    public String getEventCollection ( ) { 
        return this.eventCollection;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("event_collection")
    public void setEventCollection (String value) { 
        this.eventCollection = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("filters")
    public List<String> getFilters ( ) { 
        return this.filters;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("filters")
    public void setFilters (List<String> value) { 
        this.filters = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("interval")
    public String getInterval ( ) { 
        return this.interval;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("interval")
    public void setInterval (String value) { 
        this.interval = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("last_modified_date")
    public Date getLastModifiedDate ( ) { 
        return this.lastModifiedDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("last_modified_date")
    public void setLastModifiedDate (Date value) { 
        this.lastModifiedDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("query_name")
    public String getQueryName ( ) { 
        return this.queryName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("query_name")
    public void setQueryName (String value) { 
        this.queryName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("query_type")
    public String getQueryType ( ) { 
        return this.queryType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("query_type")
    public void setQueryType (String value) { 
        this.queryType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("timeframe")
    public Date getTimeframe ( ) { 
        return this.timeframe;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("timeframe")
    public void setTimeframe (Date value) { 
        this.timeframe = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("urls")
    public Urls getUrls ( ) { 
        return this.urls;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("urls")
    public void setUrls (Urls value) { 
        this.urls = value;
    }
 
}
 