/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class SavedQueriesListResourceResponseBuilder {
    //the instance to build
    private SavedQueriesListResourceResponse savedQueriesListResourceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SavedQueriesListResourceResponseBuilder() {
        savedQueriesListResourceResponse = new SavedQueriesListResourceResponse();
    }

    public SavedQueriesListResourceResponseBuilder analysisType(String analysisType) {
        savedQueriesListResourceResponse.setAnalysisType(analysisType);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder createdDate(Date createdDate) {
        savedQueriesListResourceResponse.setCreatedDate(createdDate);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder eventCollection(String eventCollection) {
        savedQueriesListResourceResponse.setEventCollection(eventCollection);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder filters(List<String> filters) {
        savedQueriesListResourceResponse.setFilters(filters);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder interval(String interval) {
        savedQueriesListResourceResponse.setInterval(interval);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder lastModifiedDate(Date lastModifiedDate) {
        savedQueriesListResourceResponse.setLastModifiedDate(lastModifiedDate);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder queryName(String queryName) {
        savedQueriesListResourceResponse.setQueryName(queryName);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder queryType(String queryType) {
        savedQueriesListResourceResponse.setQueryType(queryType);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder timeframe(Date timeframe) {
        savedQueriesListResourceResponse.setTimeframe(timeframe);
        return this;
    }

    public SavedQueriesListResourceResponseBuilder urls(Urls urls) {
        savedQueriesListResourceResponse.setUrls(urls);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SavedQueriesListResourceResponse build() {
        return savedQueriesListResourceResponse;
    }
}