/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SelectUniqueResourceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5285873197625769786L;
    private List<String> result;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public List<String> getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    public void setResult (List<String> value) { 
        this.result = value;
    }
 
}
 