/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class StepsBuilder {
    //the instance to build
    private Steps steps;

    /**
     * Default constructor to initialize the instance
     */
    public StepsBuilder() {
        steps = new Steps();
    }

    public StepsBuilder actorProperty(List<String> actorProperty) {
        steps.setActorProperty(actorProperty);
        return this;
    }

    public StepsBuilder eventCollection(String eventCollection) {
        steps.setEventCollection(eventCollection);
        return this;
    }

    public StepsBuilder filters(List<Filters> filters) {
        steps.setFilters(filters);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Steps build() {
        return steps;
    }
}