/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;

public class UrlsBuilder {
    //the instance to build
    private Urls urls;

    /**
     * Default constructor to initialize the instance
     */
    public UrlsBuilder() {
        urls = new Urls();
    }

    public UrlsBuilder savedQueryResultsUrl(String savedQueryResultsUrl) {
        urls.setSavedQueryResultsUrl(savedQueryResultsUrl);
        return this;
    }

    public UrlsBuilder savedQueryUrl(String savedQueryUrl) {
        urls.setSavedQueryUrl(savedQueryUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Urls build() {
        return urls;
    }
}