/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Urls 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4933465644863820168L;
    private String savedQueryResultsUrl;
    private String savedQueryUrl;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saved_query_results_url")
    public String getSavedQueryResultsUrl ( ) { 
        return this.savedQueryResultsUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saved_query_results_url")
    public void setSavedQueryResultsUrl (String value) { 
        this.savedQueryResultsUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saved_query_url")
    public String getSavedQueryUrl ( ) { 
        return this.savedQueryUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saved_query_url")
    public void setSavedQueryUrl (String value) { 
        this.savedQueryUrl = value;
    }
 
}
 