/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.keen.io";

    //its value should just be your API Key
    //TODO: Replace the authorization with an appropriate value
    public static String authorization = "";

}
