/*
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2016
 */
package io.keen.api;

import io.keen.api.controllers.*;
import io.keen.api.http.client.HttpClient;

public class KeenIoClient {
    /**
     * Singleton access to FunnelResource controller
     * @return	Returns the FunnelResourceController instance 
     */
    public FunnelResourceController getFunnelResource() {
        return FunnelResourceController.getInstance();
    }

    /**
     * Singleton access to SavedQueriesListResource controller
     * @return	Returns the SavedQueriesListResourceController instance 
     */
    public SavedQueriesListResourceController getSavedQueriesListResource() {
        return SavedQueriesListResourceController.getInstance();
    }

    /**
     * Singleton access to ExtractionResource controller
     * @return	Returns the ExtractionResourceController instance 
     */
    public ExtractionResourceController getExtractionResource() {
        return ExtractionResourceController.getInstance();
    }

    /**
     * Singleton access to SelectUniqueResource controller
     * @return	Returns the SelectUniqueResourceController instance 
     */
    public SelectUniqueResourceController getSelectUniqueResource() {
        return SelectUniqueResourceController.getInstance();
    }

    /**
     * Singleton access to SumResource controller
     * @return	Returns the SumResourceController instance 
     */
    public SumResourceController getSumResource() {
        return SumResourceController.getInstance();
    }

    /**
     * Singleton access to PercentileResource controller
     * @return	Returns the PercentileResourceController instance 
     */
    public PercentileResourceController getPercentileResource() {
        return PercentileResourceController.getInstance();
    }

    /**
     * Singleton access to MedianResource controller
     * @return	Returns the MedianResourceController instance 
     */
    public MedianResourceController getMedianResource() {
        return MedianResourceController.getInstance();
    }

    /**
     * Singleton access to AverageResource controller
     * @return	Returns the AverageResourceController instance 
     */
    public AverageResourceController getAverageResource() {
        return AverageResourceController.getInstance();
    }

    /**
     * Singleton access to MaximumResource controller
     * @return	Returns the MaximumResourceController instance 
     */
    public MaximumResourceController getMaximumResource() {
        return MaximumResourceController.getInstance();
    }

    /**
     * Singleton access to MinimumResource controller
     * @return	Returns the MinimumResourceController instance 
     */
    public MinimumResourceController getMinimumResource() {
        return MinimumResourceController.getInstance();
    }

    /**
     * Singleton access to CountUniqueResource controller
     * @return	Returns the CountUniqueResourceController instance 
     */
    public CountUniqueResourceController getCountUniqueResource() {
        return CountUniqueResourceController.getInstance();
    }

    /**
     * Singleton access to CountResource controller
     * @return	Returns the CountResourceController instance 
     */
    public CountResourceController getCountResource() {
        return CountResourceController.getInstance();
    }

    /**
     * Singleton access to EventCollectionResource controller
     * @return	Returns the EventCollectionResourceController instance 
     */
    public EventCollectionResourceController getEventCollectionResource() {
        return EventCollectionResourceController.getInstance();
    }

    /**
     * Singleton access to WardrobeResource controller
     * @return	Returns the WardrobeResourceController instance 
     */
    public WardrobeResourceController getWardrobeResource() {
        return WardrobeResourceController.getInstance();
    }

    /**
     * Singleton access to PropertyResource controller
     * @return	Returns the PropertyResourceController instance 
     */
    public PropertyResourceController getPropertyResource() {
        return PropertyResourceController.getInstance();
    }

    /**
     * Singleton access to EventResource controller
     * @return	Returns the EventResourceController instance 
     */
    public EventResourceController getEventResource() {
        return EventResourceController.getInstance();
    }

    /**
     * Singleton access to SavedQueryRowResource controller
     * @return	Returns the SavedQueryRowResourceController instance 
     */
    public SavedQueryRowResourceController getSavedQueryRowResource() {
        return SavedQueryRowResourceController.getInstance();
    }

    /**
     * Singleton access to SavedQueryRowResultResource controller
     * @return	Returns the SavedQueryRowResultResourceController instance 
     */
    public SavedQueryRowResultResourceController getSavedQueryRowResultResource() {
        return SavedQueryRowResultResourceController.getInstance();
    }

    /**
     * Singleton access to DiscoveryResource controller
     * @return	Returns the DiscoveryResourceController instance 
     */
    public DiscoveryResourceController getDiscoveryResource() {
        return DiscoveryResourceController.getInstance();
    }

    /**
     * Singleton access to ProjectsResource controller
     * @return	Returns the ProjectsResourceController instance 
     */
    public ProjectsResourceController getProjectsResource() {
        return ProjectsResourceController.getInstance();
    }

    /**
     * Singleton access to VersionsResource controller
     * @return	Returns the VersionsResourceController instance 
     */
    public VersionsResourceController getVersionsResource() {
        return VersionsResourceController.getInstance();
    }

    /**
     * Singleton access to QueriesResource controller
     * @return	Returns the QueriesResourceController instance 
     */
    public QueriesResourceController getQueriesResource() {
        return QueriesResourceController.getInstance();
    }

    /**
     * Singleton access to ProjectRowResource controller
     * @return	Returns the ProjectRowResourceController instance 
     */
    public ProjectRowResourceController getProjectRowResource() {
        return ProjectRowResourceController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public KeenIoClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public KeenIoClient(String authorization) {
        this();
        Configuration.authorization = authorization;
    }
}